version: 4.0.0
variant: cyberpunk
head:
  rss: /atom.xml
search:
  type: insight
navbar:
  # 导航栏菜单项
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
# Article related configurations
article:
  # Code highlight settings
  highlight:
    # Code highlight themes
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: dracula
    # Show copy code button
    clipboard: true
    # Default folding status of the code blocks. Can be "", "folded", "unfolded"
    fold: unfolded
  # Whether to show estimated article reading time
  readtime: true
  # Article licensing block
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: "https://creativecommons.org/licenses/by-nc/4.0/"
widgets:
  - position: left
    type: profile
    # 作者名称
    author: hulatocat
    # 作者头衔
    author_title: A GitHub Octocat
    # 作者所在地/公司
    location: GitHub Inc.
    # 头像图片地址
    avatar: https://octodex.github.com/images/hula_loop_octodex03.gif
    # 是否显示圆形头像
    avatar_rounded: false
    # Gravatar邮箱(如不设置`avatar`项)
    gravatar:
    # 关注按钮链接地址
    follow_link: "https://octodex.github.com/hulatocat"
    # 社交媒体链接
    social_links:
      Github:
        icon: fab fa-github
        url: "https://github.com/"
      Icarus: "https://github.com/ppoffice/hexo-theme-icarus"
  - type: toc
    position: left
    # 是否显示目录项目的序号
    index: true
  - position: left
    type: links
    # 友站名称与链接
    links:
      Hexo: "https://hexo.io"
      Bulma: "https://bulma.io"
      MetaNetwork: "https://meta-network.mttk.net"
  - position: right
    type: recent_posts
  # - position: right
  #   type: archives
  - position: right
    type: tags
  - position: right
    type: categories
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  # Name or URL template of the JavaScript and/or stylesheet CDN provider
  cdn: jsdelivr
  # Name or URL template of the webfont CDN provider
  fontcdn: loli
  # Name or URL of the fontawesome icon font CDN provider
  iconcdn: loli
